# Transform data
max_chunk_size: 1500
chunk_overlap: 250

# Encoding data
batch_size: 50

# LLM models
summarizer_model: 'mrm8488/bert2bert_shared-spanish-finetuned-summarization'
embedding_model: 'sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2'
llama_model: 'meta-llama/Llama-2-7b-hf'
model: 'mistralai/Mistral-7B-Instruct-v0.2'
repetition_penalty: 1.1
return_full_text: True
max_new_tokens: 1024
temperature: 0.4

# RAG configuration
top_k_docs: 10

# Prompts
pre_prompt: |
  Como un experto en derecho y leyes españolas, tu tarea es responder preguntas sobre leyes y normas en España.
  Para ello, debes tener en cuenta y utilizar el contexto proporcionado para responder de forma precisa a la pregunta del usuario.
  Deberás proporcionar detalles claros y precisos en tus respuestas, asegurándote de referenciar adecuadamente cualquier ley relacionada.
  Asegúrate de responder siempre en español. Si no conoces la respuesta, admítelo.
  Estructura correctamente tu respuesta.
prompt_context: |
  El contexto que debes usar para responder al usuario tiene un formato de lista, donde cada elemento será un diccionario con dos claves.
  La clave 'context' contendrá la información necesaria para contestar a la pregunta y la clave 'score' será una puntuación entre 0.0 y 1.0. 
  Deberás dar más importancia al contexto cuanto mayor sea el score del contexto. Referencia tus fuentes, pero no compartas el contexto proporcionado.
